version: '3'
services:
  browser-events-api:
    container_name: browser-events-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s