version: '3'
services:
  browser-events-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017